<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Hangfire.Core" Version="1.8.15" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageReference Include="MailKit" Version="4.8.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
	<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.11" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    <PackageReference Include="MimeKit" Version="4.8.0" />
    <PackageReference Include="Minio" Version="6.0.3" />
    <PackageReference Include="NCrontab.Signed" Version="3.3.3" />
    <PackageReference Include="Scrutor" Version="5.0.2" />
    <PackageReference Include="Serilog" Version="4.1.0" />
	<PackageReference Include="SkiaSharp" Version="2.88.9" />
	<PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.9" />
    <PackageReference Include="Stubble.Core" Version="1.10.8" />
    <PackageReference Include="Svg.Skia" Version="2.0.0.4" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SWIFTTAP.Infrastructure\SWIFTTAP.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>$(MSBuildProjectName).Test</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Cards\Logo\DTOs\" />
    <Folder Include="Features\Cards\Themes\Queries\" />
    <Folder Include="Features\Statistics\CardVisitGeoStatistics\Specifications\" />
    <Folder Include="Features\Statistics\VcfDownloadStatistics\DTOs\" />
  </ItemGroup>
	
</Project>
