<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>false</InvariantGlobalization>
    <UserSecretsId>a6b3a2c6-59e5-4c5e-9946-0e59d58d2ce1</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\MobileUser\**" />
    <Content Remove="Areas\MobileUser\**" />
    <EmbeddedResource Remove="Areas\MobileUser\**" />
    <None Remove="Areas\MobileUser\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.Hangfire" Version="8.0.1" />
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="8.0.2" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="8.0.1" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.15" />
    <PackageReference Include="Hangfire.Core" Version="1.8.15" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.20.10" />
    <PackageReference Include="MicroElements.Swashbuckle.FluentValidation" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.7.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SWIFTTAP.Application\SWIFTTAP.Application.csproj" />
    <ProjectReference Include="..\SWIFTTAP.Domain\SWIFTTAP.Domain.csproj" />
    <ProjectReference Include="..\SWIFTTAP.Infrastructure\SWIFTTAP.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Templates\en\AuthTwoFactor.mustache">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\en\ContactForm.mustache">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\en\CreateUser.mustache">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\en\RegisterUser.mustache">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="Templates\en\CreateAdmin.mustache">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\en\ResetPassword.mustache">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\en\ResetPasswordAsAdmin.mustache">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\pl\AuthTwoFactor.mustache">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\pl\ContactForm.mustache">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\pl\CreateUser.mustache">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\pl\RegisterUser.mustache">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\pl\CreateAdmin.mustache">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\pl\ResetPassword.mustache">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\pl\ResetPasswordAsAdmin.mustache">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
